config/routes.rb
Rails.application.routes.draw do
       
  devise_for :members, :controllers => { :registrations => "registrations" }
 

  
  root "home#index" 
  get '/members/social_sign_up' => 'members#social_sign_up'
  get '/members/timeline' => 'home#timeline'
  get '/members/update_timeline' => 'home#update_timeline'
  get '/auth/twitter/callback' => 'home#connect_twitter'
  get '/auth/google_oauth2/callback' => 'home#connect_gplus'
  get '/auth/failure' => 'members#social_sign_up'

end

app/models/google_model.rb
class GoogleModel < ActiveRecord::Base
  belongs_to :member

  #Stores url of all posts to database
  def self.store_urls(user)
	GooglePlus.access_token = user.gplus_token
   	person = GooglePlus::Person.get(user.gplus_id,:access_token => user.gplus_token) 
	gplus_activity = person.list_activities

	#checks for previous entries
	user.google_models.delete_all unless user.google_models.last.blank? 
	gplus_activity.each do |item|
	  @gplus_user = GoogleModel.new  			
	  @gplus_user.member = user
	  @gplus_user.urls = item.url.to_s
	  @gplus_user.create_date = item.published
	  @gplus_user.save
 	end
  end
end

app/models/member.rb
class Member < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :password, :email ,:presence=>true,:on=>:create

  has_many :twitter_models , dependent: :destroy
  has_many :google_models , dependent: :destroy

  #update authorised models (google plus and twitter)
  def self.update_records (user)
  	TwitterModel.store_urls(user) if user.twitter_id.present? 
    if user.gplus_id.present?
      user.token_expired?
      GoogleModel.store_urls(user) 
    end
  end

  #if google access token is expired, fetches a new one
  def token_expired?
    expiry = Time.at(self.gplus_token_expires_at.to_i) 
    if expiry < Time.now 
      data = {
              client_id: '476602585408-3fiklaclekbinfmbd2lsdjcur1u21ril.apps.googleusercontent.com',
              client_secret: 'RX-7Mq_SXT1DJSJsYJtLj6a4',
              refresh_token: self.gplus_refresh_token,
              grant_type: "refresh_token"
             }
      @response = ActiveSupport::JSON.decode(RestClient.post "https://accounts.google.com/o/oauth2/token", data)
      if @response["access_token"].present?
        self.gplus_token = @response["access_token"]
        self.gplus_token_expires_at = @response["expires_in"]
        self.save
      end
    end
  end
  
end

app/models/twitter_model.rb
class TwitterModel < ActiveRecord::Base
  belongs_to :member

  #Stores url of all posts to database
  def self.store_urls(user)
  	client = Twitter::REST::Client.new do |config|
	    config.consumer_key        = 'KFmY7FZfHs4nPCsuerXj61isy'
	    config.consumer_secret     = 'K3z9WkgHN2uAbppe7MaYRyyLJf1lCVHWHPtVpEtyyCSJFpYCHb'
	    config.access_token        = user.twitter_token
	    config.access_token_secret = user.twitter_secret
	  end

    #Checks for previous entries
    user.twitter_models.delete_all unless user.twitter_models.last.blank? 
	  tweets = client.user_timeline
  	tweets.each do |item|
    	@twitter_user = TwitterModel.new
   	  @twitter_user.urls =  item.url.to_s
   	  @twitter_user.member = user
      @twitter_user.create_date = item.created_at
   	  @twitter_user.save
	  end
  end	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #redirect to timeline page after sign in
  def after_sign_in_path_for(resource) 
   	members_timeline_path
  end

  #redirect to social signup page if twiiter connection fails
  def failure
    redirect_to members_social_sign_up_path
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def timeline
    @member = current_member
  end

  #refreshes timeline view
  def update_timeline
    Member.update_records(current_member)
    redirect_to members_timeline_path
  end
	
  #root page - checks if a user is already logged in or not
  def index
  	if current_member
  		redirect_to members_timeline_path
  	else
  		redirect_to member_session_path
  	end
  end

  #Link twitter account with timetrain account
  def connect_twitter
    auth = request.env["omniauth.auth"]
    current_member.twitter_token = auth["credentials"]["token"]
    current_member.twitter_secret = auth["credentials"]["secret"]
    current_member.twitter_id = auth["uid"]
    if current_member.img_url.blank?
      current_member.username = auth.info.name
      current_member.img_url = auth.info.image
	  end
    current_member.save
	  TwitterModel.store_urls(current_member)
	  redirect_to members_social_sign_up_path
  end

  #Link google plus account with timetrain account
  def connect_gplus
	  auth = request.env["omniauth.auth"]
	  current_member.gplus_id = auth["uid"]
    current_member.gplus_token = auth.credentials.token
    if auth.info.image.present?
      current_member.username = auth.info.name
      current_member.img_url = auth.info.image
    end
    current_member.gplus_refresh_token = auth.credentials.refresh_token
    current_member.gplus_token_expires_at = auth.credentials.expires_at
	  current_member.save
	  GoogleModel.store_urls(current_member)
	  redirect_to members_social_sign_up_path	
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController

  def new
  	@member= Member.new
  end

  #Create a new timetrain user
  def create
    @member = Member.new(member_params)
    if @member.save(member_params)
	    redirect_to social_sign_up_path
    else
	    redirect_to new_member_registration_path
    end
  end

  def social_sign_up
    @user = current_member
  end

  private
    def member_params
	    params.require(:member).permit(:username, :email, :password, :password_confirmation)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  #redirect to Social signup page after User signup
  def after_sign_up_path_for(resource)
    members_social_sign_up_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/views/home/index.html.erb
<% if member_signed_in? %>
  <h3>you have succesfully signed in</h3>
  <%= link_to "timelne", members_timeline_path, :method => :get %>
  <%= link_to "Sign Out", destroy_member_session_path, :method => :delete %>
<% else %>
  <h1> welcom to TimeTrain</h1>
  <%= link_to "Sign In", new_member_session_path, :method => :get %>
  <%= link_to "Sign up", new_member_registration_path, :method => :get %>
<% end %>

app/views/home/timeline.html.erb
<body onload="hideWid();">

  <script type="text/javascript">
    function hideWid() {

      <% current_member.google_models.each do |post| %>
        document.getElementById('g<%= post.id %>').style.display = 'none';
      <% end %>
      <% current_member.twitter_models.each do |post| %>
        document.getElementById('t<%= post.id %>').style.display = 'none';
      <% end %>
    }
    window.document.onkeydown = function (e)
      {
        if (!e) e = event;
        if (e.keyCode == 27)
          hideWid();
      }
  </script>
  <%= image_tag("logo_white.png", class: "logo") %>
  <div class="menu">
    <input type="button" id="zoomIn" title="Zoom in"/>
    <input type="button" id="zoomOut" title="Zoom out"/>
    <input type="button" id="moveLeft" title="Move left"/>
    <input type="button" id="moveRight" title="Move right"/>
    <a href="/members/update_timeline">
      <input type="button" id="reset" title="Refresh timeline"/>
    </a>
  </div>
   
  <div id="visualization"></div>
  <script type="text/javascript">
    //show / hide widgets
    function showpost(id) {

      var p = document.getElementById(id);
      if(p.style.display == 'block')
        p.style.display = 'none';
      else
        p.style.display = 'block';
    }

    //html elements creation
    

    <% current_member.google_models.each do |post| %>
      var itemg<%= post.id %> = '<a class="dotlabel" onclick="showpost(\'g<%= post.id %>\');">G</a>';
    <% end %>
    <% current_member.twitter_models.each do |post| %>
      var itemt<%= post.id %> = '<a class="dotlabel" onclick="showpost(\'t<%= post.id %>\');">G</a>';
      <% end %>
   
   
    // DOM element where the Timeline will be attached
    var container = document.getElementById('visualization');
   
    // Create a json evnt data set
    var items = new vis.DataSet([
      <% current_member.google_models.each do |post| %>
        {id: <%= post.id %>, content: itemg<%= post.id %>, start: '<%= post.create_date %>', type: 'gpoint'},
      <% end %>
      <% current_member.twitter_models.each do |post| %>
          {id: <%= 1000+post.id %>, content: itemt<%= post.id %>, start: '<%= post.create_date.to_s[0...10]+ "T" + 
                                                                    post.create_date.to_s[11...19] + "Z" %>', type: 'tpoint'},
      <% end %>
    ]);
   
    // Create a Timeline
    var timeline = new vis.Timeline(container, items, options);
   
    // attach events to the navigation buttons
    document.getElementById('zoomIn').onclick    = function () { zoom(-0.2); };
    document.getElementById('zoomOut').onclick   = function () { zoom( 0.2); };
    document.getElementById('moveLeft').onclick  = function () { move( 0.2); };
    document.getElementById('moveRight').onclick = function () { move(-0.2); };

  </script>
   
  <div class="widgets">
    <% current_member.twitter_models.each do |post| %>
      <div class="wid-tweet" id="t<%= post.id %>">
        <blockquote class="twitter-tweet" width="350"><a href="<%= post.urls %>"></a></blockquote>
      </div>
    <% end %>
    

    <% current_member.google_models.each do |post| %>
      <div class="wid-post" id="g<%= post.id %>">
        <div class="g-post" data-href="<%= post.urls %>"></div>
      </div>
    <% end %>
  </div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>timetrain</title>
	  <%= favicon_link_tag 'favicon.ico' %>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= stylesheet_link_tag "vis", media: "all" %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <script type="text/javascript" src="https://apis.google.com/js/plusone.js"></script>
    <script async src="https://platform.twitter.com/widgets.js"></script>
  	<%= csrf_meta_tags %>
	</head>
	
  <body>
	<%= yield %>
	</body>

  <!-- Footer -->
  <div id="footer">
    <p>&copy 2014 timetrain   | 
      <a href="#">About</a>   | 
      <a href="#">Contact</a> | 
      <a href="#">Help</a>
    </p>
  </div>

  <% if current_member %> 
    <div class="signout">
      <ul>
        <li>
          <%= image_tag(current_member.img_url, class: "prof_img") %>
          <ul>
            <li><%= current_member.username %></li>
            <li><%= link_to "Social sign up", members_social_sign_up_path, :method => :get %></li>
            <li><%= link_to "Sign out", destroy_member_session_path, :method => :delete %></li>
          </ul>
        </li>
      </ul>
    </div>
  <% end %>
</html>

app/views/members/social_sign_up.html.erb
<h1><%= image_tag("logo_white.png", class: "logo") %></h1>
<div id="container">
  <div class="notice">
    <% if @user.twitter_id.blank? || @user.gplus_id.blank? %>
      You may connect your accounts now
    <% else %>
      You can now continue to timetrain.
    <% end %>
  </div></br>    
  <% if @user.twitter_id.blank? %>
    <a href="/auth/twitter" class="tt twitter">Connect Twitter
  <% else %>
    <a href="#" class="tt twitterx">
    &#10004 Twitter Connected
  <% end %>  
      <span class="icons twitter"></span>
    </a>

  <% if @user.gplus_id.blank? %>
    <a href="/auth/google_oauth2" class="tt gplus">Connect Google+
  <% else %>
    <a href="#" class="tt gplusx">
    &#10004 Google+ Connected
  <% end %>  
      <span class="icons gplus"></span>
    </a>      
  <% if @user.twitter_id.blank? && @user.gplus_id.blank? %>
    <button disabled>Complete sign up</button>
  <% else %>
    <a href="/members/timeline">
      <button>Continue</button>
    </a>
  <% end %>
</div>